INSERT INTO PLAYLIST(DESCRICAO,ATIVO,ORDEM) VALUES ('Initial Playlist', 1,1);

INSERT INTO MIDIA(ARQUIVO,DURACAO,ORDEM,ID_PLAYLIST) VALUES ('Hello.avi', 10,1,1);
INSERT INTO MIDIA(ARQUIVO,DURACAO,ORDEM,ID_PLAYLIST) VALUES ('Teste.avi', 15,2,1);
INSERT INTO MIDIA(ARQUIVO,DURACAO,ORDEM,ID_PLAYLIST) VALUES ('Relogio.mpeg', 20,3,1);
INSERT INTO MIDIA(ARQUIVO,DURACAO,ORDEM,ID_PLAYLIST) VALUES ('Calendario.avi', 12,4,1);
