DROP TABLE IF EXISTS PLAYLIST;
DROP TABLE IF EXISTS MIDIA;

CREATE TABLE PLAYLIST (
  ID_PLAYLIST int(11) unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT, -- necessario para auto increment do H2
  DESCRICAO VARCHAR(300) NOT NULL,
  ATIVO INT NOT NULL,
  ORDEM INT NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE MIDIA (
  ID_MIDIA int(11) unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT, -- necessario para auto increment do H2
  ARQUIVO VARCHAR(300) NOT NULL,
  DURACAO INT NOT NULL,
  ORDEM INT NOT NULL,
  ID_PLAYLIST int(11),
  CONSTRAINT `items_ibfk_1` FOREIGN KEY (`ID_PLAYLIST`) REFERENCES `PLAYLIST` (`ID_PLAYLIST`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
